In [1]:
import pandas as pd
import numpy as np

import pymongo

from dotenv import load_dotenv
import os

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
download = False
if download:
    load_dotenv()
    mongo_username = os.getenv("mongo_username")
    mongo_password = os.getenv("mongo_password")
    
    client = pymongo.MongoClient(f"mongodb+srv://{mongo_username}:{mongo_password}@cluster0.d4ojg.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
    
    db = client.SteamDB
    
    games_collection = db.steam_games
    user_collection = db.steam_users
    user_games_collection = db.steam_user_games
    user_reviews_collection = db.steam_user_reviews
    
    games_data = list(games_collection.find())
    users_data = list(user_collection.find())
    user_games_data = list(user_games_collection.find())
    user_reviews_data = list(user_reviews_collection.find())
    
    df_games = pd.DataFrame(games_data)
    df_users = pd.DataFrame(users_data)
    df_user_games = pd.DataFrame(user_games_data)
    df_user_reviews = pd.DataFrame(user_reviews_data)
    
    df_games.to_csv('../data/raw/games_data.csv')
    df_users.to_csv('../data/raw/users_data.csv')
    df_user_games.to_csv('../data/raw/user_games_data.csv')
    df_user_reviews.to_csv('../data/raw/user_reviews_data.csv')
else:
    df_games = pd.read_csv('../data/raw/games_data.csv', index_col=0)
    df_users = pd.read_csv('../data/raw/users_data.csv', index_col=0)
    df_user_games = pd.read_csv('../data/raw/user_games_data.csv', index_col=0)
    df_user_reviews = pd.read_csv('../data/raw/user_reviews_data.csv', index_col=0)

In [3]:
df_games.drop('_id', axis=1, inplace=True)
df_users.drop('_id', axis=1, inplace=True)
df_user_games.drop('_id', axis=1, inplace=True)
df_user_reviews.drop('_id', axis=1, inplace=True)

In [3]:
df = pd.read_csv('../data/raw/steamAPI_ownedGames.csv', index_col=0)

In [4]:
condition = [
    df['playtime_forever'].between(0, 5),
    df['playtime_forever'].between(5, 15),
    df['playtime_forever'].between(15, 60),
    df['playtime_forever'].between(60, 720),
    df['playtime_forever'].between(720, 7200),
    df['playtime_forever'].between(7200, 28800),
    df['playtime_forever'].between(28800, 86400),
    df['playtime_forever'].between(86400, 172800),
    df['playtime_forever'].between(172800, 518400)]

choices = [0, 2, 2.5, 3, 3.5, 4, 4.5, 4.7, 4.9]

df['rating'] = np.select(condition, choices, 5)

In [30]:
df

                 steamid    appid  playtime_forever  rating
0      76561198123999673       50                 2     0.0
1      76561198123999673       60                83     3.0
2      76561198123999673       70              1691     3.5
3      76561198123999673      130               408     3.0
4      76561198123999673      220              4357     3.5
...                  ...      ...               ...     ...
99344  76561198207321007   880940               431     3.0
99345  76561198207321007   945360               666     3.0
99346  76561198207321007    12210                65     3.0
99347  76561198207321007  1305420                 0     0.0
99348  76561198207321007  1506830               131     3.0

[99349 rows x 4 columns]

In [4]:
df_user_games

                   userId   gameId                        Title Hours_Played
0                benedict   200510          XCOM: Enemy Unknown          120
1                benedict   289070  Sid Meier's Civilization VI          125
2                benedict    72850  The Elder Scrolls V: Skyrim           83
3                benedict    47540               Puzzle Quest 2           74
4                benedict    28050    Deus Ex: Human Revolution           36
...                   ...      ...                          ...          ...
596699  76561198106701525   291480                      Warface          1.5
596700  76561198106701525   374320         DARK SOULS\u2122 III          1.4
596701  76561198106701525   444090                     Paladins          0.4
596702  76561198106701525  1333910                     Sizeable          0.3
596703  76561198106701525   984110             SYNTHETIK: Arena          0.1

[596704 rows x 4 columns]

In [5]:
# df = pd.merge(df_user_games, df_games.drop('Title', axis=1), on=['gameId'], how='left')
df = df_games.copy()

df.drop(['Release_Date', 'Description', 'Recent_Reviews', 'All_Reviews', 'Meta_Critic_Score', 'Steam_Awards'], axis=1, inplace=True)
df.dropna(subset=['Tags'], inplace=True)

df['Genre'] = df['Genre'].fillna('')
df['Publisher'] = df['Publisher'].fillna(df['Developer'])
df['Franchise'] = df['Franchise'].fillna(df['Title'])
df['Price'] = df['Price'].fillna(0)

df.reset_index(drop=True, inplace=True)

df.Tags = df.Tags.apply(lambda x: ', '.join(x.strip('[]\'').split("', '")))
# df.Tags = df.Tags.apply(lambda x: x.strip('[]\'').split("', '"))
df.Features = df.Features.apply(lambda x: x.strip('[]\'').split("', '"))

df.info()
# df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1417 entries, 0 to 1416
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   gameId     1417 non-null   int64
 1   Title      1417 non-null   object
 2   Genre      1417 non-null   object
 3   Developer  1417 non-null   object
 4   Publisher  1417 non-null   object
 5   Franchise  1417 non-null   object
 6   Tags       1417 non-null   object
 7   Features   1417 non-null   object
 8   Price      1417 non-null   object
dtypes: int64(1), object(8)
memory usage: 99.8+ KB

In [6]:
df.head()

,gameId,Title,Genre,Developer,Publisher,Franchise,Tags,Features,Price
0,730,Counter-Strike: Global Offensive,"Action, Free to Play","Valve, Hidden Path Entertainment",Valve,Counter-Strike: Global Offensive,"FPS, Shooter, Multiplayer, Competitive, Action...","[Steam Achievements, Full controller support, ...","123,00 TL"
1,570,Dota 2,"Action, Free to Play, Strategy",Valve,Valve,Dota,"Free to Play, MOBA, Multiplayer, Strategy, eSp...","[Steam Trading Cards, Steam Workshop, SteamVR ...",0
2,578080,PUBG: BATTLEGROUNDS,"Action, Adventure, Free to Play, Massively Mul...","KRAFTON, Inc.","KRAFTON, Inc.",PUBG: BATTLEGROUNDS,"Survival, Shooter, Multiplayer, Battle Royale,...","[Online PvP, Stats, Remote Play on Phone, Remo...","109,00 TL"
3,1245620,ELDEN RING,"Action, RPG",FromSoftware Inc.,"FromSoftware Inc., BANDAI NAMCO Entertainment",ELDEN RING,"Souls-like, Relaxing, Dark Fantasy, RPG, Diffi...","[Single-player, Online PvP, Online Co-op, Stea...","499,00 TL"
4,1172470,Apex Legendsâ„¢,"Action, Adventure, Free to Play",Respawn Entertainment,Electronic Arts,Apex Legends,"Free to Play, Battle Royale, Multiplayer, Shoo...","[Online PvP, Online Co-op, Steam Achievements,...","109,00 TL"

In [7]:
cm = CountVectorizer().fit_transform(df.Tags)

In [8]:
cs = cosine_similarity(cm)

In [9]:
cs

array([[1.        , 0.56273143, 0.68810235, ..., 0.36018014, 0.11677484,
        0.06558258],
       [0.56273143, 1.        , 0.46466019, ..., 0.34669749, 0.10375717,
        0.05827165],
       [0.68810235, 0.46466019, 1.        , ..., 0.39654528, 0.09642365,
        0.10830607],
       ...,
       [0.36018014, 0.34669749, 0.39654528, ..., 1.        , 0.14019993,
        0.14763465],
       [0.11677484, 0.10375717, 0.09642365, ..., 0.14019993, 1.        ,
        0.07658396],
       [0.06558258, 0.05827165, 0.10830607, ..., 0.14763465, 0.07658396,
        1.        ]])

In [20]:
title = 'DayZ'

game_id = df[df.Title == title].index[0]

In [21]:
game_id

30

In [22]:
scores = list(enumerate(cs[game_id]))

In [23]:
sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
sorted_scores = sorted_scores[1:]

In [24]:
sorted_scores

[(1283, 0.8471737420873575),
 (535, 0.8257228238447707),
 (12, 0.7706746355884525),
 (1329, 0.7627700713964736),
 (27, 0.7624563678786219),
 (759, 0.7440729491417853),
 (878, 0.7434844114105212),
 (351, 0.7395739969534468),
 (335, 0.7356123579206248),
 (1018, 0.7309879850882872),
 (1365, 0.7265990145507549),
 (996, 0.7253235664820745),
 (115, 0.7191012094028308),
 (1196, 0.7164977208318384),
 (543, 0.7154547587901782),
 (325, 0.7068454221751481),
 (61, 0.7059781184061313),
 (102, 0.6968683416725756),
 (242, 0.6963106238227915),
 (1351, 0.6881023532039755),
 (906, 0.6827887419989188),
 (26, 0.6823230454059214),
 (249, 0.6796590597837963),
 (170, 0.6788335930269978),
 (599, 0.6784005252999683),
 (627, 0.6777389936698862),
 (1295, 0.6777389936698861),
 (94, 0.6746990849399868),
 (1403, 0.6746990849399866),
 (549, 0.6672976811635086),
 (631, 0.666666666666667),
 (1181, 0.6636648415023737),
 (191, 0.6567895774291851),
 (893, 0.6565706694547586),
 (740, 0.6560798513518474),
 (184, 0.6524726973924444),
 (1069, 0.6473388749701497),
 (45, 0.6473388749701496),
 (747, 0.6462303276414969),
 (870, 0.6462303276414969),
 (748, 0.6446583712203044),
 (848, 0.6446583712203044),
 (39, 0.6416587529241817),
 (209, 0.6371182478422788),
 (794, 0.6365239496641677),
 (380, 0.6337694342435133),
 (19, 0.6330541649476574),
 (1238, 0.6330541649476573),
 (427, 0.6269355057278585),
 (856, 0.6269355057278585),
 (117, 0.6217059141274922),
 (416, 0.6212607441973955),
 (846, 0.6212607441973955),
 (229, 0.6179143806533248),
 (373, 0.6179143806533247),
 (467, 0.6159924028072145),
 (515, 0.6154574548966637),
 (712, 0.6154574548966637),
 (109, 0.614182774643474),
 (180, 0.6132441406718665),
 (408, 0.6105716541821837),
 (440, 0.6092717958449426),
 (458, 0.6092717958449426),
 (709, 0.6092717958449426),
 (231, 0.6092717958449425),
 (719, 0.6092717958449425),
 (796, 0.6092717958449425),
 (262, 0.6060606060606062),
 (1085, 0.6060606060606062),
 (1237, 0.6060606060606062),
 (46, 0.6030226891555273),
 (544, 0.6009819973837497),
 (1218, 0.5980999726097407),
 (265, 0.597081434026532),
 (641, 0.597081434026532),
 (1253, 0.597081434026532),
 (445, 0.5970814340265319),
 (135, 0.5930216194611504),
 (1024, 0.5930216194611504),
 (483, 0.5930216194611503),
 (48, 0.5921565254637919),
 (214, 0.5909368402852792),
 (472, 0.590936840285279),
 (134, 0.5903260526902472),
 (818, 0.5846845821518306),
 (531, 0.5818573654517123),
 (1222, 0.5815526314990443),
 (510, 0.580370430699081),
 (563, 0.580370430699081),
 (172, 0.5802588531856595),
 (38, 0.5780059766913395),
 (116, 0.5780059766913395),
 (130, 0.5757575757575759),
 (811, 0.5757575757575759),
 (1108, 0.5757575757575759),
 (213, 0.5757575757575758),
 (224, 0.5723638070321426),
 (1019, 0.5723638070321425),
 (1040, 0.5723638070321425),
 (1074, 0.5723638070321425),
 (1185, 0.5723638070321425),
 (88, 0.5720775535473552),
 (114, 0.5720775535473552),
 (385, 0.5720775535473552),
 (628, 0.5720775535473552),
 (53, 0.5709136102183889),
 (1324, 0.5709136102183888),
 (557, 0.5708992257184503),
 (140, 0.5695214286468868),
 (879, 0.5685352436149614),
 (344, 0.5672273623252053),
 (457, 0.5672273623252053),
 (488, 0.5672273623252053),
 (83, 0.564782494724905),
 (492, 0.5640760748177663),
 (23, 0.5640760748177662),
 (541, 0.5590653920196748),
 (1301, 0.5590653920196748),
 (1084, 0.5586203877309281),
 (986, 0.5539117094069974),
 (36, 0.5539117094069973),
 (1378, 0.5539117094069973),
 (31, 0.5512459105263767),
 (356, 0.5512459105263765),
 (207, 0.5504818825631804),
 (1408, 0.5495319562599505),
 (832, 0.5462309935991351),
 (86, 0.5454545454545455),
 (762, 0.5454545454545455),
 (798, 0.5454545454545455),
 (564, 0.5448686650003407),
 (898, 0.5448686650003407),
 (145, 0.5437456166805353),
 (292, 0.5437456166805353),
 (664, 0.5416025603090641),
 (8, 0.5402954672391689),
 (1020, 0.5373732906238788),
 (1387, 0.5373732906238787),
 (973, 0.5365433699886598),
 (710, 0.5330017908890264),
 (1279, 0.5296408977028497),
 (1332, 0.5296408977028497),
 (24, 0.5296199396711575),
 (289, 0.5296199396711575),
 (340, 0.5276448530110864),
 (309, 0.5263613559678152),
 (731, 0.5263613559678152),
 (281, 0.5263613559678151),
 (418, 0.5263613559678151),
 (2, 0.5248638810814781),
 (908, 0.5231388366621642),
 (1187, 0.5231388366621642),
 (234, 0.5222329678670936),
 (301, 0.5222329678670936),
 (755, 0.5222329678670936),
 (851, 0.5222329678670936),
 (1043, 0.5222329678670936),
 (888, 0.5222329678670935),
 (406, 0.518999296107682),
 (529, 0.5172065470681888),
 (768, 0.5172065470681888),
 (844, 0.5151515151515154),
 (40, 0.5151274263289283),
 (1138, 0.5151274263289283),
 (1342, 0.5103545438827409),
 (680, 0.5085133809309825),
 (793, 0.5085133809309825),
 (1031, 0.5085133809309825),
 (171, 0.5083042452524146),
 (965, 0.5083042452524146),
 (339, 0.5075192189225521),
 (233, 0.502518907629606),
 (648, 0.502518907629606),
 (1259, 0.502518907629606),
 (15, 0.5002443195845779),
 (11, 0.5002164033860247),
 (654, 0.5002164033860247),
 (694, 0.5002164033860247),
 (756, 0.5002164033860247),
 (1162, 0.5002164033860247),
 (256, 0.4986206870274042),
 (677, 0.4974683381630912),
 (619, 0.49543369430686235),
 (49, 0.4932200252078106),
 (1323, 0.492365963917331),
 (85, 0.49236596391733095),
 (121, 0.49236596391733095),
 (552, 0.48766065222237814),
 (1265, 0.48766065222237814),
 (559, 0.48741743667595394),
 (1136, 0.4865092359773211),
 (198, 0.484881137876427),
 (297, 0.484881137876427),
 (994, 0.484881137876427),
 (96, 0.48484848484848503),
 (1247, 0.48484848484848503),
 (589, 0.4848484848484849),
 (142, 0.48247525236638356),
 (828, 0.48006512051616934),
 (1241, 0.48006512051616934),
 (511, 0.4800651205161693),
 (267, 0.4779521193992432),
 (1110, 0.4778386858817091),
 (236, 0.47766514722122555),
 (679, 0.47766514722122555),
 (976, 0.47766514722122555),
 (1054, 0.47766514722122555),
 (205, 0.4767312946227961),
 (520, 0.4767312946227961),
 (1128, 0.4767312946227961),
 (1346, 0.4767312946227961),
 (375, 0.4738704723373514),
 (71, 0.47237749297333026),
 (355, 0.4707919090691997),
 (686, 0.4707919090691997),
 (105, 0.4690176471209656),
 (412, 0.4690176471209656),
 (774, 0.4690176471209656),
 (1371, 0.4690176471209656),
 (93, 0.4689790496105418),
 (182, 0.4689790496105418),
 (573, 0.4689790496105418),
 (1126, 0.4689790496105418),
 (685, 0.4642070825485277),
 (106, 0.46420708254852766),
 (736, 0.46420708254852766),
 (1118, 0.4642070825485276),
 (136, 0.4621681606529815),
 (491, 0.4621681606529815),
 (489, 0.4621681606529814),
 (922, 0.4615930911724978),
 (596, 0.4605661864718383),
 (128, 0.4605661864718382),
 (42, 0.457891045625714),
 (253, 0.457891045625714),
 (931, 0.457891045625714),
 (598, 0.45663301294771563),
 (632, 0.4566330129477156),
 (452, 0.4545454545454547),
 (579, 0.4545454545454547),
 (604, 0.4526019054848144),
 (636, 0.4526019054848144),
 (603, 0.4525557286846652),
 (730, 0.4525557286846652),
 (812, 0.4525557286846652),
 (299, 0.4522670168666455),
 (7, 0.4518259957799241),
 (646, 0.4518259957799241),
 (770, 0.45182599577992405),
 (1075, 0.45182599577992405),
 (90, 0.4512920922216141),
 (413, 0.4512920922216141),
 (35, 0.44781107551989896),
 (243, 0.44781107551989896),
 (711, 0.44781107551989896),
 (968, 0.4476282581717944),
 (883, 0.4459957386704485),
 (146, 0.4459957386704484),
 (512, 0.4459957386704484),
 (1191, 0.4459957386704484),
 (1318, 0.4459957386704484),
 (215, 0.44599573867044834),
 (202, 0.4449492083146097),
 (283, 0.4449492083146097),
 (320, 0.4449492083146097),
 (682, 0.4449492083146097),
 (777, 0.4449492083146097),
 (112, 0.44381268229929727),
 (449, 0.44381268229929727),
 (788, 0.44381268229929727),
 (943, 0.44381268229929727),
 (1100, 0.44197999993927367),
 (317, 0.44136741475237473),
 (345, 0.44136741475237473),
 (1025, 0.44038550605054433),
 (64, 0.43876345447627835),
 (330, 0.4377137796365057),
 (642, 0.4377137796365057),
 (1014, 0.4377137796365057),
 (560, 0.4363279519884436),
 (402, 0.43557240518437673),
 (129, 0.4355163866123252),
 (423, 0.4351941398892447),
 (464, 0.4351941398892447),
 (226, 0.43498179826162964),
 (415, 0.43498179826162964),
 (328, 0.4349817982616295),
 (1003, 0.4308202184276646),
 (148, 0.43082021842766455),
 (333, 0.43082021842766455),
 (312, 0.4297722474802028),
 (28, 0.42927285527410686),
 (324, 0.42927285527410686),
 (1150, 0.42927285527410686),
 (54, 0.4276686017238498),
 (110, 0.4276686017238498),
 (617, 0.4276686017238498),
 (1268, 0.4276686017238498),
 (913, 0.42766860172384974),
 (216, 0.4264014327112211),
 (854, 0.4264014327112211),
 (1116, 0.4264014327112211),
 (839, 0.42640143271122094),
 (1273, 0.4242424242424244),
 (322, 0.42424242424242437),
 (310, 0.4235868710436788),
 (394, 0.4235868710436788),
 (1004, 0.42220033092074905),
 (805, 0.4202303194929034),
 (82, 0.4198911048651824),
 (179, 0.41795700381857237),
 (382, 0.41795700381857237),
 (876, 0.41795700381857237),
 (1412, 0.41795700381857237),
 (706, 0.41785544701867267),
 (66, 0.4177863742936748),
 (420, 0.4177863742936748),
 (546, 0.4177863742936748),
 (676, 0.4177863742936748),
 (1276, 0.4177863742936748),
 (522, 0.41778637429367477),
 (296, 0.4131671220064233),
 (308, 0.4131671220064233),
 (437, 0.4131671220064233),
 (1097, 0.4131671220064233),
 (1246, 0.4131671220064233),
 (99, 0.41286141192238535),
 (60, 0.4128614119223853),
 (346, 0.41286141192238524),
 (746, 0.4119429204355498),
 (270, 0.41194292043554975),
 (507, 0.41194292043554975),
 (1067, 0.41194292043554975),
 (376, 0.4106616018714763),
 (561, 0.40967324519935133),
 (1089, 0.40967324519935133),
 (285, 0.4096732451993513),
 (166, 0.4077954358702778),
 (391, 0.4077954358702778),
 (399, 0.40779543587027767),
 (987, 0.40779543587027767),
 (138, 0.4064485096624696),
 (174, 0.4064485096624696),
 (601, 0.4064485096624696),
 (1391, 0.40626937289522047),
 (571, 0.4061811972299618),
 (795, 0.4061811972299617),
 (411, 0.40618119722996165),
 (610, 0.40618119722996165),
 (1289, 0.4061811972299616),
 (998, 0.4029114820126902),
 (1368, 0.4029114820126902),
 (478, 0.402015126103685),
 (132, 0.4020151261036848),
 (426, 0.4020151261036848),
 (909, 0.4020151261036848),
 (650, 0.40065466492249974),
 (708, 0.40065466492249974),
 (1114, 0.40065466492249974),
 (1154, 0.40065466492249974),
 (1233, 0.40065466492249974),
 (1236, 0.40065466492249974),
 (1409, 0.40065466492249974),
 (592, 0.40004734568283146),
 (1028, 0.40004734568283146),
 (1056, 0.40004734568283146),
 (580, 0.4000473456828314),
 (691, 0.4000473456828314),
 (4, 0.40004734568283135),
 (495, 0.40004734568283135),
 (1087, 0.3993615319154359),
 (822, 0.39927470475234533),
 (833, 0.39927470475234533),
 (1396, 0.39927470475234533),
 (252, 0.3953477463074336),
 (666, 0.39477101697586137),
 (819, 0.39477101697586137),
 (1319, 0.39477101697586137),
 (1352, 0.39477101697586137),
 (738, 0.3947710169758613),
 (925, 0.3939393939393941),
 (717, 0.39393939393939403),
 (1005, 0.39393939393939403),
 (1219, 0.39393939393939403),
 (829, 0.39364791081110856),
 (923, 0.3936479108111085),
 (896, 0.390867979985286),
 (804, 0.38810293211724584),
 (34, 0.3881029321172458),
 (1245, 0.3881029321172458),
 (754, 0.3879049103011416),
 (763, 0.3879049103011416),
 (1270, 0.3862436396682141),
 (1254, 0.3853373177942263),
 (1039, 0.38533731779422625),
 (653, 0.38499525175450905),
 (853, 0.38499525175450905),
 (1195, 0.3825824798870484),
 (624, 0.3825184261187248),
 (1123, 0.3825184261187248),
 (0, 0.3813850356982369),
 (89, 0.3813850356982369),
 (104, 0.3813850356982369),
 (635, 0.3813850356982369),
 (950, 0.3813850356982369),
 (1290, 0.3813850356982369),
 (378, 0.3806090734789259),
 (1339, 0.3806090734789259),
 (388, 0.3771682545706787),
 (113, 0.3768891807222046),
 (583, 0.3760507165451775),
 (101, 0.3755338080994054),
 (456, 0.3755338080994054),
 (1207, 0.3755338080994054),
 (799, 0.3751832396884335),
 (946, 0.3751832396884335),
 (1094, 0.3751832396884335),
 (1242, 0.3751832396884335),
 (1308, 0.3751832396884334),
 (173, 0.3730235484764953),
 (300, 0.3730235484764953),
 (313, 0.3720364745708926),
 (651, 0.3720364745708926),
 (945, 0.3720364745708926),
 (1161, 0.3720364745708926),
 (1251, 0.3720364745708926),
 (1414, 0.3720364745708926),
 (521, 0.37165231124132925),
 (386, 0.36927447293799825),
 (352, 0.3692744729379982),
 (367, 0.3692744729379982),
 (745, 0.3692744729379982),
 (1027, 0.3692744729379982),
 (1189, 0.3692744729379982),
 (383, 0.36851386559504445),
 (669, 0.36851386559504445),
 (1141, 0.3685138655950444),
 (496, 0.3674047167570346),
 (43, 0.3671086215711883),
 (68, 0.3671086215711883),
 (542, 0.3671086215711883),
 (594, 0.3671086215711883),
 (438, 0.36563621206356534),
 (1202, 0.36563621206356534),
 (477, 0.36363636363636376),
 (517, 0.3636363636363637),
 (570, 0.3636363636363637),
 (605, 0.3636363636363637),
 (1135, 0.36297700432031393),
 (1091, 0.3621034121889507),
 (836, 0.36187343222787294),
 (1077, 0.3594253787238923),
 (867, 0.3593289016375418),
 (75, 0.3582488604159192),
 (315, 0.3582488604159192),
 (963, 0.3582488604159192),
 (1002, 0.3582488604159192),
 (3, 0.35781322366606727),
 (72, 0.35781322366606727),
 (337, 0.3555795011093798),
 (914, 0.3555795011093798),
 (962, 0.3555795011093798),
 (364, 0.3554857012833179),
 (866, 0.3553345272593509),
 (74, 0.35533452725935083),
 (228, 0.35533452725935083),
 (1384, 0.35533452725935083),
 (144, 0.3530939318018998),
 (361, 0.3530939318018998),
 (629, 0.3530939318018998),
 (825, 0.3530939318018998),
 (1147, 0.3530939318018998),
 (1411, 0.3517632353407243),
 (466, 0.35032452487268534),
 (858, 0.35032452487268534),
 (183, 0.3496029493900505),
 (311, 0.3496029493900505),
 (673, 0.3496029493900505),
 (1093, 0.3496029493900505),
 (1179, 0.3496029493900505),
 (1311, 0.3496029493900505),
 (211, 0.3491899510776649),
 (971, 0.3481553119113958),
 (869, 0.34815531191139576),
 (81, 0.3481553119113957),
 (326, 0.3481553119113957),
 (1153, 0.3481553119113957),
 (1310, 0.3481553119113957),
 (533, 0.34815531191139565),
 (1399, 0.34815531191139565),
 (1032, 0.3451057175812343),
 (156, 0.34510571758123426),
 (692, 0.34510571758123426),
 (749, 0.34510571758123426),
 (1168, 0.34465617474213167),
 (52, 0.34401397986945),
 (6, 0.34391796971439736),
 (526, 0.34391796971439736),
 (644, 0.34391796971439736),
 (952, 0.34391796971439736),
 (1227, 0.34391796971439736),
 (1288, 0.34391796971439736),
 (13, 0.3434182842192855),
 (87, 0.3434182842192855),
 (126, 0.3434182842192855),
 (960, 0.3434182842192855),
 (1230, 0.3418817293789139),
 (400, 0.34139437099945946),
 (841, 0.34139437099945946),
 (932, 0.3411615227029607),
 (286, 0.33886949683494305),
 (927, 0.33886949683494305),
 (1200, 0.33886949683494305),
 (476, 0.33850160019316505),
 (558, 0.338501600193165),
 (1239, 0.338501600193165),
 (1062, 0.3379631847096874),
 (595, 0.33796318470968734),
 (672, 0.3373495424699933),
 (791, 0.3373495424699933),
 (944, 0.3373495424699933),
 (70, 0.33501260508640407),
 (194, 0.33501260508640407),
 (208, 0.33501260508640407),
 (661, 0.33501260508640407),
 (165, 0.335012605086404),
 (1267, 0.335012605086404),
 (622, 0.33475966990116734),
 (645, 0.3344968040028363),
 (1080, 0.3343253990189949),
 (656, 0.3333333333333334),
 (760, 0.3333333333333334),
 (17, 0.33164555877539403),
 (802, 0.33161826621403645),
 (970, 0.3302891295379082),
 (201, 0.3289758474798845),
 (280, 0.3289758474798845),
 (275, 0.32897584747988445),
 (1388, 0.32897584747988445),
 (33, 0.3283947887145926),
 (196, 0.3283947887145926),
 (248, 0.3283947887145926),
 (1389, 0.3283947887145926),
 (1325, 0.3282439759448873),
 (436, 0.32667930388828254),
 (782, 0.32667930388828254),
 (141, 0.326637289959244),
 (720, 0.326637289959244),
 (602, 0.32623634869622214),
 (707, 0.32566947363946486),
 (1393, 0.3236694374850748),
 (425, 0.323254091917618),
 (735, 0.323254091917618),
 (1334, 0.3223291856101522),
 (789, 0.32232918561015217),
 (823, 0.3200052246177461),
 (771, 0.3198010745334158),
 (972, 0.3198010745334158),
 (92, 0.3198010745334157),
 (516, 0.3191423692521128),
 (1398, 0.3191423692521128),
 (737, 0.3191423692521127),
 (865, 0.3185591239211394),
 (989, 0.31855912392113933),
 (77, 0.3178208630818641),
 (291, 0.3178208630818641),
 (474, 0.3178208630818641),
 (830, 0.3178208630818641),
 (158, 0.31688471712175664),
 (222, 0.3149183286488868),
 (508, 0.3149183286488868),
 (734, 0.3149183286488868),
 (1053, 0.3149183286488868),
 (5, 0.3148000938676784),
 (767, 0.3148000938676784),
 (773, 0.3143473067309657),
 (306, 0.313822957230424),
 (985, 0.31333978072025614),
 (1397, 0.31333978072025614),
 (1117, 0.3133397807202561),
 (1149, 0.3133397807202561),
 (1382, 0.3133397807202561),
 (221, 0.31265269974036125),
 (750, 0.31265269974036125),
 (911, 0.31265269974036125),
 (1205, 0.31265269974036125),
 (21, 0.3113995776646092),
 (347, 0.3108482649082268),
 (901, 0.3106303720986978),
 (1096, 0.3106303720986978),
 (1142, 0.3106303720986978),
 (1297, 0.31063037209869776),
 (690, 0.30799620140360723),
 (660, 0.30772872744833185),
 (958, 0.30772872744833185),
 (1127, 0.30772872744833185),
 (718, 0.3077287274483318),
 (1392, 0.3077287274483318),
 (562, 0.3072549338995135),
 (815, 0.3072549338995135),
 (131, 0.30725493389951347),
 (250, 0.30725493389951347),
 (817, 0.30725493389951347),
 (824, 0.30725493389951347),
 (937, 0.30725493389951347),
 (1140, 0.30725493389951347),
 (422, 0.3066220703359333),
 (1208, 0.30463589792247125),
 (1244, 0.3038948705590346),
 (699, 0.3030303030303031),
 (1282, 0.3030303030303031),
 (1298, 0.3030303030303031),
 (1092, 0.30276503540974925),
 (189, 0.3027650354097492),
 (572, 0.3027650354097492),
 (1275, 0.3027650354097492),
 (1375, 0.3027650354097492),
 (462, 0.30276503540974914),
 (1229, 0.3015113445777637),
 (25, 0.30151134457776363),
 (111, 0.30151134457776363),
 (269, 0.30151134457776363),
 (294, 0.30151134457776363),
 (319, 0.30151134457776363),
 (681, 0.30151134457776363),
 (389, 0.29998469504883835),
 (103, 0.29904998630487034),
 (288, 0.29904998630487034),
 (481, 0.29904998630487034),
 (537, 0.29904998630487034),
 (892, 0.29904998630487034),
 (1104, 0.29904998630487034),
 (1132, 0.29904998630487034),
 (1166, 0.29904998630487034),
 (167, 0.298540717013266),
 (369, 0.298540717013266),
 (698, 0.298540717013266),
 (1274, 0.298540717013266),
 (266, 0.2969078476100822),
 (649, 0.296078262731896),
 (975, 0.296078262731896),
 (949, 0.29554023164452436),
 (1060, 0.2954684201426395),
 (890, 0.2954684201426394),
 (80, 0.29424494316824984),
 (1064, 0.29424494316824984),
 (1081, 0.29424494316824984),
 (47, 0.29250896965085227),
 (1349, 0.29250896965085227),
 (967, 0.2909286827258562),
 (1354, 0.2909286827258562),
 (800, 0.29038160345625114),
 (1360, 0.29038160345625114),
 (63, 0.2901294265928298),
 (188, 0.2901294265928298),
 (192, 0.2901294265928298),
 (528, 0.2901294265928298),
 (667, 0.2901294265928298),
 (849, 0.2901294265928298),
 (993, 0.2901294265928298),
 (1042, 0.2901294265928298),
 (22, 0.29012942659282975),
 (772, 0.2896827297511606),
 (1134, 0.2896827297511606),
 (1143, 0.2872134789517764),
 (137, 0.2869368599152863),
 (57, 0.28618190351607126),
 (107, 0.28618190351607126),
 (178, 0.28618190351607126),
 (473, 0.28618190351607126),
 (1012, 0.28618190351607126),
 (14, 0.28603877677367767),
 (177, 0.28603877677367767),
 (241, 0.28603877677367767),
 (969, 0.28603877677367767),
 (1182, 0.28603877677367767),
 (1176, 0.2854496128592251),
 (410, 0.28426762180748066),
 (268, 0.2823912473624526),
 (775, 0.2823912473624526),
 (1, 0.2823912473624525),
 (451, 0.2823912473624525),
 (524, 0.2823912473624525),
 (1183, 0.28232985128663995),
 (358, 0.28138742976632514),
 (640, 0.28138742976632514),
 (743, 0.2813874297663251),
 (864, 0.2795530723408051),
 (758, 0.2793101938654641),
 (65, 0.2791452631195413),
 (190, 0.2791452631195413),
 (1353, 0.2791452631195413),
 (1101, 0.2787473366690303),
 (897, 0.27852424952911653),
 (69, 0.27695585470349865),
 (200, 0.27695585470349865),
 (251, 0.27695585470349865),
 (1194, 0.27695585470349865),
 (73, 0.27524094128159016),
 (245, 0.27524094128159016),
 (1405, 0.27524094128159016),
 (32, 0.2735506022160966),
 (977, 0.2735506022160966),
 (360, 0.2731154967995676),
 (634, 0.2731154967995676),

In [25]:
j=0
game_titles=[]
recommendation=[]
print('The 10 most recommended games to', title, 'are:\n')
for item in sorted_scores:
    game_title = df[df.index == item[0]]['Title'].values[0]
    game_titles.append(game_title)
    print(j+1, game_title)
    j+=1
    if j>9:
        break

The 10 most recommended games to DayZ are:

1 Miscreated
2 No More Room in Hell
3 Rust
4 Survarium
5 Unturned
6 Infestation: The New Z
7 S.T.A.L.K.E.R.: Call of Pripyat
8 Beasts of Bermuda
9 Stay Out
10 S.T.A.L.K.E.R.: Clear Sky

In [16]:
df_user_reviews = df_user_reviews.copy()
df_user_reviews['Recomendation'] = np.where(df_user_reviews.Recomendation == "Recommended", 1, -1)

df_games_reviews = pd.merge(df_user_games, df_user_reviews, on=['gameId', 'userId'], how='left')

df_games_reviews['Recomendation'] = df_games_reviews['Recomendation'].fillna(0)
df_games_reviews['Review_Time'] = df_games_reviews['Review_Time'].fillna(0)
df_games_reviews['Comment'] = df_games_reviews['Comment'].fillna('')

df_games_reviews.reset_index(drop=True, inplace=True)

df_games_reviews

,userId,gameId,Title,Hours_Played,Recomendation,Review_Time,Comment
0,benedict,200510,XCOM: Enemy Unknown,120,1.0,120.3,Went back to this game as a preparation for Xc...
1,benedict,289070,Sid Meier's Civilization VI,125,0.0,0,
2,benedict,72850,The Elder Scrolls V: Skyrim,83,1.0,69.9,One of the best games ever
3,benedict,47540,Puzzle Quest 2,74,0.0,0,
4,benedict,28050,Deus Ex: Human Revolution,36,0.0,0,
...,...,...,...,...,...,...,...
596699,76561198106701525,291480,Warface,1.5,0.0,0,
596700,76561198106701525,374320,DARK SOULS\u2122 III,1.4,0.0,0,
596701,76561198106701525,444090,Paladins,0.4,0.0,0,
596702,76561198106701525,1333910,Sizeable,0.3,0.0,0,
596703,76561198106701525,984110,SYNTHETIK: Arena,0.1,0.0,0,

In [17]:
df2 = df_games_reviews[df_games_reviews.Title.isin(game_titles)]

In [18]:
df2.loc[:, ['userId', 'Title', 'Hours_Played', 'Recomendation']][df2['userId']=="-scape-"]

        userId        Title Hours_Played  Recomendation
63558  -scape-    Half-Life         11.6            0.0
63560  -scape-       Portal          4.0            1.0
63581  -scape-  Half-Life 2          2.6            0.0
63588  -scape-     Portal 2          8.9            0.0

In [19]:
df_wide = pd.pivot_table(df2, index='Title', columns='userId', values='Recomendation', aggfunc=np.sum)
df_wide.shape

(33, 2716)

In [20]:
df_wide = df_wide.fillna(0)
df_wide.iloc[:10, 0:5]

userId,-Dutch-,-Maniac,-__7355608__-,-scape-,011010010110111001101111
Title,,,,,
ANNO: Mutationem,0.0,0.0,0.0,0.0,0.0
Alice: Madness Returns,0.0,0.0,0.0,0.0,0.0
Biped,0.0,0.0,0.0,0.0,0.0
Black Mesa,0.0,0.0,0.0,0.0,0.0
Borderlands 2,0.0,0.0,0.0,0.0,0.0
Borderlands: The Pre-Sequel,0.0,0.0,0.0,0.0,0.0
Celeste,0.0,0.0,0.0,0.0,0.0
Charlie's Adventure,0.0,0.0,0.0,0.0,0.0
Crab Game,0.0,0.0,0.0,0.0,0.0
DDraceNetwork,0.0,0.0,0.0,0.0,0.0

In [21]:
# import distance methods
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import manhattan_distances
from sklearn.metrics.pairwise import euclidean_distances

In [22]:
dists = cosine_similarity(df_wide)
dists

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
dists = pd.DataFrame(dists, columns=df_wide.index)

dists.index = dists.columns
dists.iloc[0:10, 0:10]

Title,ANNO: Mutationem,Alice: Madness Returns,Biped,Black Mesa,Borderlands 2,Borderlands: The Pre-Sequel,Celeste,Charlie's Adventure,Crab Game,DDraceNetwork
Title,,,,,,,,,,
ANNO: Mutationem,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
Alice: Madness Returns,0.0,1.000000,0.0,0.000000,0.101535,0.000000,0.000000,0.000000,0.000000,0.0
Biped,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
Black Mesa,0.0,0.000000,0.0,1.000000,0.079993,0.000000,0.031846,0.000000,0.043769,0.0
Borderlands 2,0.0,0.101535,0.0,0.079993,1.000000,0.152302,0.024626,0.050767,0.050767,0.0
Borderlands: The Pre-Sequel,0.0,0.000000,0.0,0.000000,0.152302,1.000000,0.121268,0.125000,0.041667,0.0
Celeste,0.0,0.000000,0.0,0.031846,0.024626,0.121268,1.000000,0.000000,0.040423,0.0
Charlie's Adventure,0.0,0.000000,0.0,0.000000,0.050767,0.125000,0.000000,1.000000,0.000000,0.0
Crab Game,0.0,0.000000,0.0,0.043769,0.050767,0.041667,0.040423,0.000000,1.000000,0.0
DDraceNetwork,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

In [24]:
games_i_like = [title]
dists[games_i_like].head()

Title                   Portal 2
Title
ANNO: Mutationem        0.000000
Alice: Madness Returns  0.000000
Biped                   0.000000
Black Mesa              0.106991
Borderlands 2           0.147080

In [25]:
games_summed = np.sum(dists[games_i_like], axis=1)

In [26]:
games_summed = games_summed.sort_values(ascending=False)
games_summed

Title
Portal 2                                1.000000
Half-Life 2                             0.229039
Portal                                  0.223520
Half-Life                               0.161669
Borderlands 2                           0.147080
Black Mesa                              0.106991
Halo: The Master Chief Collection       0.098812
Human: Fall Flat                        0.096511
Celeste                                 0.087833
Tomb Raider                             0.081893
Little Nightmares                       0.078406
Neverwinter Nights: Enhanced Edition    0.064018
Death's Door                            0.064018
It Takes Two                            0.034219
Ori and the Blind Forest                0.032009
Crab Game                               0.030179
Halo Infinite                           0.027298
Borderlands: The Pre-Sequel             0.022634
Saints Row IV                           0.018107
Salt and Sanctuary                      0.000000
Time in Time                            0.000000
The Outer Worlds                        0.000000
Trine 4: The Nightmare Prince           0.000000
Supraland                               0.000000
Unravel Two                             0.000000
ANNO: Mutationem                        0.000000
Ori and the Will of the Wisps           0.000000
Little Nightmares II                    0.000000
Alice: Madness Returns                  0.000000
DDraceNetwork                           0.000000
Charlie's Adventure                     0.000000
Biped                                   0.000000
Upside Down                             0.000000
dtype: float64

In [27]:
ranked_games = games_summed.index[games_summed.index.isin(games_i_like)==False]
ranked_games = ranked_games.tolist()
ranked_games[:5]

['Half-Life 2', 'Portal', 'Half-Life', 'Borderlands 2', 'Black Mesa']

In [28]:
def get_similar(games, n=None):
    """
    calculates which games are most similar to the inputs. Must not return
    the games that were inputted.
    
    Parameters
    ----------
    games: list
        some games!
    
    Returns
    -------
    ranked_games: list
        rank ordered games
    """
    games = [game for game in games if game in dists.columns]
    games_summed = dists[games].apply(lambda row: np.sum(row), axis=1)
    games_summed = games_summed.sort_values(ascending=False)
    ranked_games = games_summed.index[games_summed.index.isin(games)==False]
    ranked_games = ranked_games.tolist()
    if n is None:
        return ranked_games
    else:
        return ranked_games[:n]

In [29]:
for game in get_similar(title, 10):
    print(game)

ANNO: Mutationem
Little Nightmares
Unravel Two
Trine 4: The Nightmare Prince
Tomb Raider
Time in Time
The Outer Worlds
Supraland
Salt and Sanctuary
Saints Row IV

In [30]:
for i, game in enumerate(get_similar(title, 10)):
    print("%d) %s" % (i+1, game))

1) ANNO: Mutationem
2) Little Nightmares
3) Unravel Two
4) Trine 4: The Nightmare Prince
5) Tomb Raider
6) Time in Time
7) The Outer Worlds
8) Supraland
9) Salt and Sanctuary
10) Saints Row IV

In [31]:
# Alien: Isolation

In [32]:
df[df.Title=="It Takes Two"]

,gameId,Title,Genre,Developer,Publisher,Franchise,Tags,Features,Price
52,1426210,It Takes Two,"Action, Adventure",Hazelight,Electronic Arts,EA Originals,"Co-op, Split Screen, Multiplayer, Adventure, P...","[Online Co-op, Shared/Split Screen Co-op, Stea...",It Takes Two Friend's Pass

In [2]:
df_tags = pd.read_csv('../data/processed/data.csv', index_col=0)
df_games = pd.read_csv('../data/raw/steamAPI_ownedGames.csv', index_col=0)

condition = [
    df_games['playtime_forever'].between(0, 5),
    df_games['playtime_forever'].between(5, 15),
    df_games['playtime_forever'].between(15, 60),
    df_games['playtime_forever'].between(60, 720),
    df_games['playtime_forever'].between(720, 7200),
    df_games['playtime_forever'].between(7200, 28800),
    df_games['playtime_forever'].between(28800, 86400),
    df_games['playtime_forever'].between(86400, 172800),
    df_games['playtime_forever'].between(172800, 518400)]

choices = [0, 2, 2.5, 3, 3.5, 4, 4.5, 4.7, 4.9]

df_games['rating'] = np.select(condition, choices, 5)

In [3]:
cm = CountVectorizer().fit_transform(df_tags.tags)

cs = cosine_similarity(cm)

In [30]:
def recommend(title):
    game_id = df_tags[df_tags.title == title].index[0]
    
    scores = list(enumerate(cs[game_id]))
    
    sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
    sorted_scores = sorted_scores[1:]
    
    top=10
    recommendation=[]
    for item in sorted_scores[:top]:
        game_id_title = df_tags.loc[df_tags.index == item[0], ['appid', 'title']].values[0]
        recommendation.append(game_id_title)
    
    df_rec = pd.DataFrame(recommendation, columns=['appid', 'title'])

    df = pd.merge(df_rec, df_games, on=['appid'])

    df_wide = pd.pivot_table(df, index='appid', columns='steamid', values='rating', aggfunc=np.sum)

    df_wide = df_wide.fillna(0)

    dists = cosine_similarity(df_wide)

    dists = pd.DataFrame(dists, columns=df_wide.index)

    dists.index = dists.columns

    n = 10
    games = df[df['title']==title]

    games = [game for game in games if game in dists.columns]
    games_summed = dists[games].apply(lambda row: np.sum(row), axis=1)
    games_summed = games_summed.sort_values(ascending=False)
    ranked_games = games_summed.index[games_summed.index.isin(games)==False]
    ranked_games = ranked_games.to_list()
    if n is None:
        return ranked_games
    else:
        return ranked_games[:n]

In [32]:
recommend('Dota 2')

[9900, 212740, 223630, 235340, 236110, 339280, 360620, 427270, 795580, 1226470]